### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-1-evaluacion-intermedia-AnadelaJara#1]
Muy buen trabajo @AnadelaJara!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `a` en el menu, dentro de los `li`.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño (usa el padding en los enlaces cuando los pongas).

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, **márcala como completada en este issue** y su súbela a este repo.

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja escribe por slack al coordinador de Adalab.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Creando** para buscar el título de la página. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by AnadelaJara** [comment]
La primera recomendación no la entiendo... :)
Los font-size están puestos en las clases, por lo que no lo he modificado. No lo he marcado como hecho por si acaso. 

Gracias!

**Comment by igarrido-adalab** [comment]
Perfecto!
